-- Opt-in API MFA: when enabled, publish/yank/owner changes (API token or cookie)
-- require a recent passkey verification (short-lived grant) or a one-time OTP.
ALTER TABLE users
    ADD COLUMN IF NOT EXISTS api_mfa_enabled BOOLEAN NOT NULL DEFAULT FALSE;
COMMENT ON COLUMN users.api_mfa_enabled IS
    'When true, publish/yank/change-owners (token or cookie) require passkey step-up';

-- safety-assured:start
--
-- All tables and indexes below are created together and are empty during this
-- migration, so non-concurrent index creation cannot block live table writes.
-- The integer foreign keys intentionally match the referenced integer IDs.

CREATE TABLE IF NOT EXISTS webauthn_credentials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    -- Raw WebAuthn credential ID (unique across users)
    credential_id BYTEA NOT NULL,
    -- Serialized webauthn_rs::prelude::Passkey
    passkey_json JSONB NOT NULL,
    name VARCHAR NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_used_at TIMESTAMPTZ
);
CREATE UNIQUE INDEX IF NOT EXISTS webauthn_credentials_credential_id_idx
    ON webauthn_credentials (credential_id);
CREATE INDEX IF NOT EXISTS webauthn_credentials_user_id_idx
    ON webauthn_credentials (user_id);
COMMENT ON TABLE webauthn_credentials IS
    'Passkeys / WebAuthn credentials registered for API MFA step-up';

-- Short-lived authorization after a successful passkey verification.
-- NULL operation = wildcard (manual "Authorize for 15 minutes").
CREATE TABLE IF NOT EXISTS api_mfa_grants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    -- When set, grant only covers this operation; NULL means any operation.
    operation VARCHAR,
    -- When set with operation, grant only covers this crate.
    crate_name VARCHAR,
    -- SHA-256 of the exact server-parsed mutation. NULL only for cookie wildcard grants.
    mutation_fingerprint BYTEA,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS api_mfa_grants_user_expires_idx
    ON api_mfa_grants (user_id, expires_at);
CREATE INDEX IF NOT EXISTS api_mfa_grants_expires_at_idx
    ON api_mfa_grants (expires_at);
COMMENT ON TABLE api_mfa_grants IS
    'Time-bounded grants issued after passkey verification for API MFA';
COMMENT ON COLUMN api_mfa_grants.operation IS
    'When set, grant only covers this operation; NULL means any operation (manual authorize)';
COMMENT ON COLUMN api_mfa_grants.crate_name IS
    'When set with operation, grant only covers this crate; NULL with operation is unused';

-- CLI challenge flow (RubyGems-style): create challenge → verify passkey in browser → OTP.
CREATE TABLE IF NOT EXISTS api_mfa_challenges (
    -- Public opaque token used in verification URLs
    id VARCHAR PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    api_token_id INTEGER REFERENCES api_tokens (id) ON DELETE SET NULL,
    -- Dangerous operation that triggered this challenge (publish, yank, change-owners, …)
    operation VARCHAR NOT NULL,
    -- Optional crate involved in the operation
    crate_name VARCHAR,
    -- SHA-256 of the exact server-parsed mutation
    mutation_fingerprint BYTEA NOT NULL,
    -- Human-readable, server-generated description shown on the verification page
    operation_summary VARCHAR NOT NULL,
    -- Optional localhost port for posting the OTP back to the CLI
    localhost_port INTEGER,
    -- Serialized PasskeyAuthentication state while the ceremony is in progress
    auth_state_json JSONB,
    -- SHA-256 of the one-time OTP, set after successful passkey verification
    hashed_otp BYTEA,
    -- Encrypted OTP for callback-secret-authenticated browser recovery after reload
    sealed_otp VARCHAR,
    verified_at TIMESTAMPTZ,
    otp_consumed_at TIMESTAMPTZ,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT api_mfa_challenges_localhost_port_range
        CHECK (localhost_port IS NULL OR (localhost_port >= 1024 AND localhost_port <= 65535))
);
CREATE INDEX IF NOT EXISTS api_mfa_challenges_user_id_idx
    ON api_mfa_challenges (user_id);
CREATE INDEX IF NOT EXISTS api_mfa_challenges_pending_op_idx
    ON api_mfa_challenges (api_token_id, operation, crate_name, mutation_fingerprint, expires_at)
    WHERE verified_at IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS api_mfa_challenges_pending_unique_idx
    ON api_mfa_challenges (api_token_id, operation, (COALESCE(crate_name, '')), mutation_fingerprint)
    WHERE verified_at IS NULL AND api_token_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS api_mfa_challenges_pending_user_idx
    ON api_mfa_challenges (user_id)
    WHERE verified_at IS NULL;
CREATE INDEX IF NOT EXISTS api_mfa_challenges_expires_at_idx
    ON api_mfa_challenges (expires_at);
COMMENT ON TABLE api_mfa_challenges IS
    'Short-lived API MFA operation challenges for CLI passkey acknowledgment';
COMMENT ON COLUMN api_mfa_challenges.operation IS
    'Dangerous operation that triggered this challenge (publish, yank, change-owners, …)';
COMMENT ON COLUMN api_mfa_challenges.crate_name IS
    'Optional crate involved in the operation';
COMMENT ON COLUMN api_mfa_challenges.mutation_fingerprint IS
    'SHA-256 binding the challenge to the exact server-parsed mutation';
COMMENT ON COLUMN api_mfa_challenges.operation_summary IS
    'Human-readable, server-generated description of the exact mutation';

-- Token buckets for unauthenticated challenge capability URLs. The key is a
-- server-derived hash of challenge id + client IP, never a user id.
CREATE TABLE IF NOT EXISTS api_mfa_rate_limit_buckets (
    bucket_key VARCHAR NOT NULL,
    action INTEGER NOT NULL,
    tokens INTEGER NOT NULL,
    last_refill TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (bucket_key, action)
);
COMMENT ON TABLE api_mfa_rate_limit_buckets IS
    'IP-and-capability-scoped token buckets for unauthenticated API MFA endpoints';

-- Server-side WebAuthn ceremony state (registration / manual authorize).
-- Keeps PasskeyRegistration / PasskeyAuthentication off client session cookies.
CREATE TABLE IF NOT EXISTS webauthn_ceremony_states (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    -- `registration` or `authentication`
    kind VARCHAR NOT NULL,
    state_json JSONB NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT webauthn_ceremony_states_kind_check
        CHECK (kind IN ('registration', 'authentication'))
);
CREATE UNIQUE INDEX IF NOT EXISTS webauthn_ceremony_states_user_kind_idx
    ON webauthn_ceremony_states (user_id, kind);
CREATE INDEX IF NOT EXISTS webauthn_ceremony_states_expires_at_idx
    ON webauthn_ceremony_states (expires_at);
COMMENT ON TABLE webauthn_ceremony_states IS
    'In-progress WebAuthn ceremony state for API MFA register/authorize flows';

-- Email OTP for API MFA bootstrap / recovery (enable, disable, first/recovery passkey enroll).
-- Not used as a factor for publish/yank/owner challenges (those remain passkey-only).
CREATE TABLE IF NOT EXISTS api_mfa_email_otps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    -- SHA-256 of the plaintext OTP
    hashed_otp BYTEA NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- At most one unused non-expired OTP per user (resend replaces).
CREATE UNIQUE INDEX IF NOT EXISTS api_mfa_email_otps_active_user_idx
    ON api_mfa_email_otps (user_id)
    WHERE consumed_at IS NULL;
CREATE INDEX IF NOT EXISTS api_mfa_email_otps_expires_at_idx
    ON api_mfa_email_otps (expires_at);

COMMENT ON TABLE api_mfa_email_otps IS
    'Short-lived email OTPs for API MFA enable/disable and passkey enrollment recovery';

-- safety-assured:end
